### ISSUE TITLE
插入主键为空的元组后，再插入数据，正确但数据表无法更新显示

### ISSUE THREAD

**Issue by zhengyichen123** [WU-SUNFLOWER/BusTubTracerCore#5]
先执行 insert into teacher values (null,'zyc',20);
再执行 insert into teacher values (22,'cc',20);

**Comment by WU-SUNFLOWER** [comment]
你说的是在前端Home页面插入新数据之后，在Storage或者Index面板不更新吗？

**Comment by WU-SUNFLOWER** [comment]
fixed in BusTubTracerFront 2024.12.09 version.
